# Generated by Django 6.0.5 on 2026-06-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("website", "سایت"),
                            ("mobile", "اپلیکیشن"),
                            ("ai", "هوش مصنوعی"),
                            ("bot", "بات"),
                            ("automation", "اتوماسیون"),
                        ],
                        max_length=50,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "image",
                    models.ImageField(upload_to="portfolio/", verbose_name="تصویر"),
                ),
                (
                    "technologies",
                    models.JSONField(default=list, verbose_name="تکنولوژی\u200cها"),
                ),
                ("live_url", models.URLField(blank=True, verbose_name="لینک زنده")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "نمونه کار",
                "verbose_name_plural": "نمونه کارها",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
