# Generated by Django 6.0.5 on 2026-06-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("website", "طراحی سایت"),
                            ("mobile", "اپلیکیشن موبایل"),
                            ("ai", "هوش مصنوعی"),
                            ("automation", "اتوماسیون و بات"),
                            ("network", "شبکه و امنیت"),
                            ("backend", "بک\u200cاند و API"),
                            ("other", "سایر"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sub_type", models.CharField(blank=True, max_length=100)),
                ("features", models.JSONField(default=list)),
                ("budget_range", models.CharField(max_length=100)),
                ("deadline", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="orders/"),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("referral", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("reviewing", "در حال بررسی"),
                            ("in_progress", "در حال انجام"),
                            ("delivered", "تحویل داده شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارشات",
                "ordering": ["-created_at"],
            },
        ),
    ]
